services:

  postgres:
    image: postgres:16
    container_name: batch-streaming-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: batch_streaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    image: batch-streaming:latest
    container_name: batch-streaming-etl
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: batch_streaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: